version: '3.7'

services:
  web:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - .:/usr/share/nginx/html  # Подключаем весь проект как корневую директорию
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем конфиг Nginx
      - ./ssl:/etc/ssl  # Подключаем сертификаты SSL (если нужен HTTPS)
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet

  ssl_cert:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./ssl:/etc/ssl

networks:
  webnet:
    driver: bridge